function(KillInSourceBuild)
    get_filename_component(src_dir "${CMAKE_SOURCE_DIR}" REALPATH)
    get_filename_component(bin_dir "${CMAKE_BINARY_DIR}" REALPATH)

    if("${src_dir}" STREQUAL "${bin_dir}")
        message("#######################################################################")
        message("ERROR: You cannot configure and build from within the source directory.")
        message("Please run cmake in a separate directory.")
        message("For example:")
        message("    $ cd ${CMAKE_SOURCE_DIR}")
        message("    $ mkdir build")
        message("    $ cd build")
        message("    $ cmake ..")
        message("Your attempt to build here has created:")
        message("    - 'CMakeCache.txt' file")
        message("    - 'CMakeFiles' directory.")
        message("Please remove these.")
        message("#######################################################################")
        message(FATAL_ERROR "Quitting configuration")
    endif()
endfunction()

KillInSourceBuild()
